In [1]:
import pandas as pd
import numpy as np  

df = pd.read_csv("P675 DATASET.csv", parse_dates=["Date"]) #importing the dataset and parsing the "Date" column as datetime
df.sample(5) #Displaying 5 ramdom rows

,Date,Open,High,Low,Close,Adj Close,Volume
877,2015-06-30,125.570000,126.120003,124.860001,125.430000,115.389328,44370700
1457,2017-10-17,159.779999,160.869995,159.229996,160.470001,154.134949,18997300
461,2013-11-01,74.860001,74.971428,73.691429,74.290001,66.008629,68722500
138,2012-07-20,87.575714,87.777145,86.242859,86.328575,74.599937,99367800
1926,2019-08-29,208.500000,209.320007,206.660004,209.009995,206.956604,20990500

In [2]:
df.info() #information about the dataset

<class 'pandas.DataFrame'>
RangeIndex: 2011 entries, 0 to 2010
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       2011 non-null   datetime64[us]
 1   Open       2011 non-null   float64
 2   High       2011 non-null   float64
 3   Low        2011 non-null   float64
 4   Close      2011 non-null   float64
 5   Adj Close  2011 non-null   float64
 6   Volume     2011 non-null   int64
dtypes: datetime64[us](1), float64(5), int64(1)
memory usage: 110.1 KB

In [3]:
df.isnull().sum() #checking for null values in the dataset

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [4]:
df.duplicated().sum() #checking for duplicates in the dataset

np.int64(0)

In [5]:
df.set_index('Date', inplace=True) #setting the "Date" column as the index of the dataframe

In [11]:
close_col = df.pop('Close')
df['Close'] = close_col
df.sample(5)

,Open,High,Low,Adj Close,Volume,Close
Date,,,,,,
2015-07-15,125.720001,127.150002,125.580002,116.668060,33649200,126.820000
2015-12-09,117.639999,117.690002,115.080002,107.303421,46361400,115.620003
2017-03-15,139.410004,140.750000,139.029999,133.834778,25691800,140.460007
2019-03-06,174.669998,175.490005,173.940002,171.490967,20810400,174.520004
2018-03-29,167.809998,171.750000,166.899994,162.395126,38398500,167.779999

In [12]:
import plotly.express as px

fig = px.line(df, x=df.index, y='Close', title='Close Price')
fig.show()

In [19]:
fig = px.imshow(df.corr(),text_auto='.2f',color_continuous_scale='Viridis',title='Correlation Heatmap')
fig.update_layout(width=700,height=600)
fig.update_xaxes(tickangle=90)
fig.show()